steps:
  # Deploy FE to Prod
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-prod
    entrypoint: gcloud
    args:
      - "beta"
      - "run"
      - "deploy"
      - "$_CONTAINER_NAME"
      - "--image"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME"
      - "--region"
      - "${_REGION}"
      - "--project"
      - "${_PROD_PROJECT_ID}"
      - "--max-instances"
      - "1"
      - "--cpu"
      - "2"
      - "--memory"
      - "2Gi"
      - "--concurrency"
      - "40"
      - "--service-account"
      - "${_CLOUD_RUN_APP_SA_NAME}@${_PROD_PROJECT_ID}.iam.gserviceaccount.com"
      - "--allow-unauthenticated"
      - "--iap"
      - "--set-env-vars"
      - "COMMIT_SHA=${COMMIT_SHA},REGION=${_REGION},LOG_LEVEL=${_LOG_LEVEL},REMOTE_AGENT_ENGINE_ID=${_REMOTE_AGENT_ENGINE_ID},BUCKET_NAME=${_BUCKET_NAME}"

  - name: "python:3.11-slim" 
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        pip install uv --user && uv sync --frozen
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  - name: "python:3.11-slim"
    id: trigger-deployment
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        uv export --no-hashes --no-header --no-emit-project --frozen > .requirements.txt
        uv run app/agent_engine_app.py \
          --project ${_PROD_PROJECT_ID} \
          --location ${_REGION} \
          --set-env-vars COMMIT_SHA=${COMMIT_SHA}
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

substitutions:
  _PROD_PROJECT_ID: YOUR_PROD_PROJECT_ID
  _REGION: europe-west1

logsBucket: gs://${PROJECT_ID}-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
